# Generated by Django 4.1 on 2022-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.CharField(max_length=200)),
                ('datas', models.JSONField()),
                ('datas_stats', models.CharField(max_length=200)),
                ('date_updated', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Iframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.CharField(max_length=200)),
                ('iframe_url', models.URLField()),
                ('iframe_stats', models.CharField(max_length=200)),
                ('date_updated', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MatchsAVenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('championship', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_cards_for_average', models.FloatField()),
                ('away_team_cards_for_average', models.FloatField()),
                ('home_team_cards_against_average', models.FloatField()),
                ('away_team_cards_against_average', models.FloatField()),
                ('home_team_corners_for_average', models.FloatField()),
                ('away_team_corners_for_average', models.FloatField()),
                ('home_team_corners_against_average', models.FloatField()),
                ('away_team_corners_against_average', models.FloatField()),
                ('card_bet', models.CharField(max_length=10)),
                ('corner_bet', models.CharField(max_length=10)),
            ],
        ),
    ]
