# Generated by Django 4.1 on 2022-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsavenir',
            name='real_cards',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='real_corners',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
